### ISSUE TITLE
Translate: Five Crimes at Crimson Alley

### ISSUE THREAD

**Issue by antontimmermans** [antontimmermans/MOMFCCA#1]
For translation support this file is available:
https://docs.google.com/spreadsheets/d/1xcN5kll0L8am_Ko-hGJO-ngjUGA6vJ3sK1w6h2_pI-0/edit#gid=0

You can edit the shared file. 
When you are confident about the result, you can: 
- create the localization file of your translation and attach it to this ticket. 
- If you don't know how that works, it is also fine to just leave me a message on Discord or on this ticket.

Note that the initial translation is made by google translate and it is translated from English. The meaning of the text may have gone lost in translation, so please check with the original text what message was intended. 
Google translate also may have translated words like {clue} or {agility}. These words are Keywords and must NOT be translated. Please try to keep the syntax, such as `\n, <b>, </i>, {c:QItemName}, {qst:ONECLUE}` intact. These are text formatting and code lookups, so won't need to be translated. You can verify (or copy) the correct syntax in the original English column.

Thank you in advance for your translation support. Your contribution is valuable and much appreciated. It allows more players to enjoy the scenarios.

**Comment by vidimus** [comment]
Thanks for your hard work making the scenarios "translator-friendly", @antontimmermans (apart from creating the scenarios as well, but that's secondary...   :-P  ).
