### ISSUE TITLE
Voiceover

### ISSUE THREAD

**Issue by Steve-racer** [antontimmermans/MOMFCCA#2]
[crimsonVO.zip](https://github.com/antontimmermans/MOMFCCA/files/5252514/crimsonVO.zip)

**Comment by antontimmermans** [comment]
Exactly the right atmosphere and the text adjustments are perfect. 

Thank you very much. The next scenario release will contain the voiceovers. And ofcourse I will mention your contribution in the credits.

**Comment by antontimmermans** [comment]
Released in Version 1.3
